service: aws-node-sqs-worker-project
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    QUEUE_URL: ${param:QUEUE_URL}
  region: 'ap-northeast-2'


constructs:
  jobs:
    type: queue
    worker:
      handler: index.consumer
    queueUrl: ${param:QUEUE_URL}

functions:
  producer:
    handler: index.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${param:QUEUE_URL}

plugins:
  - serverless-lift
  - serverless-dotenv-plugin
